# -*- coding: utf-8 -*-
"""Simple flask app.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15wgiV3noyh_1fi6Ppefm0g4XI-TGgqO7

# Simple flask app predicting diabetes
"""

from flask import Flask, request
import numpy as np
import pickle

model = pickle.load(open('model.pkl','rb'))

app = Flask(__name__)

def model_predict(value):
  return model.predict(value)

@app.route('/predict')
def predictions():
  value = request.args.get('value')
  prediction = model_predict(np.arange(int(value), 11).reshape(1,-1))
  return f'the result is {prediction}!'

if __name__ == '__main__':
    		app.run('localhost', 5000)